SET C51INC=D:\Keil_vn\C51\Inc;D:\Keil_vn\C51\Inc\Atmel
SET C51LIB=D:\Keil_vn\C51\Lib
SET CPU_TYPE=AT89C52
SET CPU_VENDOR=Atmel
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x016E3600
"D:\Keil_vn\C51\BIN\C51.EXE" @.\Objects\main.__i
"D:\Keil_vn\C51\BIN\C51.EXE" @.\Objects\LCD1602.__i
"D:\Keil_vn\C51\BIN\C51.EXE" @.\Objects\Timer0.__i
"D:\Keil_vn\C51\BIN\C51.EXE" @.\Objects\delaytime10us.__i
"D:\Keil_vn\C51\BIN\C51.EXE" @.\Objects\MotorRun.__i
